// <auto-generated />
namespace DataAccsessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migwriterrole : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migwriterrole));
        
        string IMigrationMetadata.Id
        {
            get { return "202106211512396_mig-writer-role"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
